apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-lite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-lite
  template:
    metadata:
      labels:
        app: rest-lite
      name: rest-lite
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pai-master
                operator: In
                values:
                - 'true'
      containers:
      - command:
        - python
        - rest.py
        - --k8s_api
        - https://default-e80a1e75.hcp.westus2.azmk8s.io:443
        - --fs_uri
        - nfs://1.1.1.1
        - --ca
        - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --bearer
        - /var/run/secrets/kubernetes.io/serviceaccount/token
        image: docker.io/xudifsd/rest-lite:latest
        imagePullPolicy: Always
        name: rest-lite
        resources:
          limits:
            memory: 256Mi
      hostNetwork: true
      imagePullSecrets:
      - name: pai-secret

